/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        File fileInput = new File("flowers.BMP");
        File fileOutput=new File("app/src/main/resources/flowers1.BMP");

        myBitmapMethod(fileInput,fileOutput);
        File newFileInput=new File("bmp_13.BMP");
        File newFileOutput=new File("app/src/main/resources/bmp_131.BMP");
        myBitmapMethod(newFileInput,newFileOutput);
        File newFileInput22=new File("sun.BMP");
        File newFileOutput22=new File("app/src/main/resources/sun11.BMP");
        myBitmapMethod(newFileInput22,newFileOutput22);

        System.out.println("done");

    }

    public static void myBitmapMethod(File input, File output) throws IOException {
        BufferedImage bufferedImage = ImageIO.read(input);
        int width = bufferedImage.getWidth();
        int height = bufferedImage.getHeight();

        BufferedImage blackOne=new BufferedImage(width,height,BufferedImage.TYPE_INT_RGB);
        for (int index = 0; index < height; index++) {
            for (int secondIndex = 0; secondIndex < width; secondIndex++) {
             Color  color =new Color( bufferedImage.getRGB( secondIndex,index));
             int red=color.getRed();
             int green=color.getGreen();
             int blue=color.getBlue();
             int alpha=color.getAlpha();
             int gr=(red+green+blue)/3;
             Color newColor=new Color(gr,gr,gr,alpha);
             blackOne.setRGB(secondIndex,index,newColor.getRGB());


            }
        }ImageIO.write(blackOne,"BMP",output);
    }
    public static void myBitmapMethod(){}

}
